### ISSUE TITLE
Move Combine muspinsim into the production server? 

### ISSUE THREAD

**Issue by leandro-liborio** [muon-spectroscopy-computational-project/muon-galaxy-tools#133]
I think it works well.  SHouldn't we move it into the production instance?

**Comment by patrick-austin** [comment]
Is now released on Toolshed and installed

**Comment by bgruening** [comment]
Do we need to do anything here for EU?

**Comment by patrick-austin** [comment]
The tool in question would be added by https://github.com/usegalaxy-eu/usegalaxy-eu-tools/pull/608/files (along with version updates for most of the other tools).
