### ISSUE TITLE
generate spectrum

### ISSUE THREAD

**Issue by subindev-d** [muon-spectroscopy-computational-project/muon-galaxy-tools#147]
Mudirac has an option to generate spectrum by setting the parameter write_spec = True,

- [ ] Add an option to generate a spectrum
- [ ] Generate the spectrum as an image if requested

**Comment by leandro-liborio** [comment]
Hi Subin,

When will you put it in the dev-server?

**Comment by subindev-d** [comment]
> Hi Subin,
> 
> When will you put it in the dev-server?

hi, It is still on development
