### ISSUE TITLE
Migrate repeated XML to a dedicated macros file

### ISSUE THREAD

**Issue by elichad** [muon-spectroscopy-computational-project/muon-galaxy-tools#76]
If we make our tools a 'suite' we can use shared macros across many tools.

https://planemo.readthedocs.io/en/latest/writing_standalone.html#macros

**Comment by bgruening** [comment]
Suites makes a lot of sense if all tools are very similar. But you can also use macros without suites. E.g. have a "global" or shared macro and simply symlink it into your subdirectories.

Using a suite or not probably depends a bit if you are going to update tools often in one go, or if you want to update single tools more often then others. E.g. are the dependencies almost the same?

**Comment by patrick-austin** [comment]
We are now using a symlinked macro file across relevant tools.
