### ISSUE TITLE
Update tools to use pymuonsuite 0.2.3 and muspinsim 1.2.0

### ISSUE THREAD

**Issue by elichad** [muon-spectroscopy-computational-project/muon-galaxy-tools#83]
Requires getting the containers built first (the last point on the [package maintenance checklist](https://github.com/muon-spectroscopy-computational-project/Developer-notes/blob/main/package-maintenance.md))

edit: actually, the containers should be built by merging a PR with these updates, thanks to [planemo-monitor](https://github.com/galaxyproject/planemo-monitor/)

**Comment by elichad** [comment]
@patrick-austin Once pm-nq is merged, recommend doing this issue, and then merging `dev` to `main` to get everything built and deployed to the ToolShed. There's a bunch of commits in `dev` that we should actually release!

**Comment by patrick-austin** [comment]
Merged updated wrappers into main, published to toolshed and installed on our isntances.
